#!/bin/bash
#Samba share settings GUI for Linux Lite
#Licence GPLv2
#Command: /usr/bin/su-to-root -X -c /path/to/cnss-gui
#Depends: zenity
#

TITLE="Lite Shares"

function first_time() {
		if ! zenity --question --title="$TITLE" --text="First time setup should be only runned once!\nYour current /etc/samba/smb.conf will be backed up,\nDo you want to continue?"; then
			return
		fi

#----Displays users with id greater than 1000 and less than 60000
#----Adds FALSE and TRUE (TRUE only on the first) and
#----stores everything in an aray
LL_LIST_H+=($(awk -F':' '$3>=1000 && $3<=60000 {print "FALSE", $1}' /etc/passwd |sed '0,/FALSE/s/FALSE/TRUE/'))

#User selection dialog
user="$(zenity --title="Add a user to Samba" --list --radiolist --text="Select a user name you wish to add to Samba." --column="Select" --column="Username" --width=325  --height=300  "${LL_LIST_H[@]}")"
      # Cancel
	if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                      unset LL_LIST_H
                      return
	fi

unset LL_LIST_H

#Workgroup selection dialog. On cancel selects the default value
group=$(zenity --title="$TITLE" --entry --entry-text=WORKGROUP --text="Enter the name of the workgroup:" --cancel-label="Use Default")
  if [ $? = 1 ]; then
	group="WORKGROUP"
  fi



#Hostname selection dialog. On cancel selects the default value
hostname=$(zenity --title="$TITLE" --entry-text=lite --entry --text="Enter the name of your computer (hostname):" --cancel-label="Use Default")
  if [ $? = 1 ]; then
	hostname="lite"
  fi

if zenity --question --title="$TITLE" --text="Do you want to add a share?"; then
#Share description input
share=$(zenity --title="$TITLE" --entry --text="Enter a short name for the share with no blank spaces in the name. \n Examples: music or my-music ")
	if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                      unset share
	fi
	
	#If the user entered special chars, abort
	if [[ "$share" =~ [^0-9a-z-A-Z] ]]; then
		zenity --warning \
		--title="" --text="Share name can contain alphanumeric characters only\nShare can not be added!"
	 	      unset share
	fi

    if [ ! -z "$share" ]; then
      cd ~
      #Path selection directory for the share
        path="$(zenity --title="Select a folder to share" --file-selection --directory)"

	#Check if the output is a path
        echo "$path" | grep "/"
	if [  $? -ne 0  ]; then
                      zenity --error --text="You must select a valid directory\nShare will not be added"
                      unset path
                     unset share
	fi
       #Check if the directory exists
       if [ ! -d $path ]; then
                       zenity --error --text="You must select a valid directory\nShare will not be added"
                       unset path
                      unset share
        fi
      fi


fi

    if zenity --question --text="You selected:\nWorkgroup: <b>$group</b>\nHostname: <b>$hostname</b>\nUsername:<b>$user</b>\nShare name:<b>$share</b>\nShare:<b>$path</b>\nDo you want to continue?"; then
	#Ask for password, pass variables and run the script
	gksudo -m "You need to provide your password in order to add users." --  env user="$user" group="$group" hostname="$hostname" share="$share" path="$path" /usr/scripts/samba/cnss-first-time
    fi

}

function add_user() {
#----Displays users with id greater than 1000 and less than 60000
#----Adds FALSE and TRUE (TRUE only on the first) and
#----stores everything in an aray
LL_LIST_H+=($(awk -F':' '$3>=1000 && $3<=60000 {print "FALSE", $1}' /etc/passwd |sed '0,/FALSE/s/FALSE/TRUE/'))

#User selection dialog
user="$(zenity --title="Add a user to Samba" --list --radiolist --text="Select a user name you wish to add to Samba." --column="Select" --column="Username" --width=325  --height=300  "${LL_LIST_H[@]}")"
      # Cancel
	if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                      unset LL_LIST_H
                      return
	fi

if grep  '^<'$user'> = "<'$user'>"$'  /etc/samba/smbusers; then
    	zenity --warning \
		--title="$TITLE" --text="Username is allready added\nUser can not be added!\nUse change user password instead."
return
fi

#Ask for password, pass variables and run the script
gksudo -m "You need to provide your password in order to add users." --  env user="$user" /usr/scripts/samba/cnss-add-user

unset LL_LIST_H
return
}

function ch_password() {
#get list of added smb users from /etc/samba/smbusers 
LL_LIST_H+=($(awk '{print "FALSE", $1}' /etc/samba/smbusers | sed 's/[<>]//g' |sed '0,/FALSE/s/FALSE/TRUE/'))

if [ -z ${LL_LIST_H[@]} ]; then
    	zenity --warning \
		--title="$TITLE" --text="No user found\nAdd a user first."
    return
fi

#User selection dialog
user="$(zenity --title="Change Samba Password" --list --radiolist --text="Select a user name to change the password." --column="Select" --column="Username" --width=325  --height=300  "${LL_LIST_H[@]}")"
      # Cancel
	if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                      unset LL_LIST_H
                      return
	fi


#Ask for password, pass variables and run the script
gksudo -m "You need to provide your password in order change users's Samba password." --  env user="$user" /usr/scripts/samba/cnss-chpasswd

unset LL_LIST_H
return
}


#Function that adds share
function add_share() {
#Share description input
share=$(zenity --title="$TITLE" --entry --text="Enter a short name for the share with no blank spaces in the name. \n Examples: music or my-music ")
	if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                      return
	fi
	
	#If the user entered special chars, abort
	if [[ "$share" =~ [^0-9a-z-A-Z] ]]; then
		zenity --warning \
		--title="" --text="Share name can contain alphanumeric characters only\nShare can not be added!"
	 	return
	fi

conf=$(cat /etc/samba/smb.conf | grep "^\[$share\]")
if [[ ! -z "$conf" ]]; then
		zenity --warning \
		--title="" --text="Share name allready exists\nShare can not be added!"
	 	return
fi

#Path selection directory for the share
path="$(zenity --title="Select a folder to share" --file-selection --directory)"

	#Check if the output is a path
        echo "$path" | grep "/"
	if [  $? -ne 0  ]; then
                      zenity --error --text="You must select a valid directory"
                      return
	fi
       #Check if the directory exists
       if [ ! -d $path ]; then
                       zenity --error --text="You must select a valid directory"
                       return
        fi



gksudo -m "You need to provide your password in order to add shares to SAMBA." --  env path="$path" share="$share" /bin/bash -c '

	echo ["$share"] >> /etc/samba/smb.conf

	echo path = "$path" >> /etc/samba/smb.conf
	echo "available = yes" >> /etc/samba/smb.conf
	echo "valid users = %U %G" >> /etc/samba/smb.conf
	echo "write list = %U" >> /etc/samba/smb.conf
	echo browsable = yes >> /etc/samba/smb.conf
	echo public = no >> /etc/samba/smb.conf
	echo writable = yes >> /etc/samba/smb.conf

	echo "guest ok = no" >> /etc/samba/smb.conf
	echo "read only = no" >> /etc/samba/smb.conf
	echo "printable = no" >> /etc/samba/smb.conf
	echo "locking = no" >> /etc/samba/smb.conf
	echo "strict locking = no" >> /etc/samba/smb.conf
	echo -e "\n" >> /etc/samba/smb.conf'

return
}

function restore_prev() {
#If the file exists offers to restore  previous network share settings
if [ -f /etc/samba/smb.conf.backup ]; then
    gksudo -m "You need to provide your password for restoring previous netwotk share settings." -- /bin/bash -c '
	if zenity --question --title="$TITLE" --text="This will restore your previous network share settings.\n\nIf you proceed your current settings will be backed up.\n\nDo you want to continue?"; then
		mv -f /etc/samba/smb.conf /etc/samba/smb.conf.backup_
		mv -f /etc/samba/smb.conf.backup /etc/samba/smb.conf
	        mv -f /etc/samba/smb.conf.backup_  /etc/samba/smb.conf.backup
		exit
	else
		exit
	fi'
else
	zenity --info --title="$TITLE" --text="No previous settings found."
	return
fi
}

function restart_network() {
#Restarts network services
gksudo -m "You need to provide your password in order to restart network services." --   /usr/scripts/samba/restart_network

return
}

function rem_share() {
#remove shares
gksudo -m "You need to provide your password in order to remove network shares."  /usr/scripts/samba/cnss-remove
return
}


while (true); do
CHOICE=$(zenity --list --radiolist --title="$TITLE" --width=350 --height=500 --column=Select --column=Task \
FALSE "Run first time setup" \
TRUE "Show Shares" \
FALSE "Add a User" \
FALSE "Change User Password" \
FALSE "Add a Share" \
FALSE "Remove a Share" \
FALSE "Edit the config file" \
FALSE "Restart Network Services" \
FALSE "Restore Previous Settings" \
FALSE "Exit" )

#If canceled exit
if [ $? = 1 ]; then
	exit 0
fi
case $CHOICE in
"Run first time setup") first_time
;;
"Show Shares") zenity --text-info --width=500  --height=600 --title="Show Samba Shares" </etc/samba/smb.conf
;;
"Add a User" )add_user
;;
"Change User Password") ch_password
;;
"Add a Share") add_share
;;
"Remove a Share") rem_share
;;
"Edit the config file" ) gksudo -m "You need to provide your password in order to edit network shares." --  env sharename="$sharename" /bin/bash -c 'exo-open /etc/samba/smb.conf'
;;
"Restart Network Services") restart_network
;;
"Restore Previous Settings") restore_prev
;;
"Exit") exit 0
;;
esac
done

exit 0
