#!/bin/bash
         TITLE="Lite Shares"
         stdbuf -oL /bin/bash \-c '(sudo service smbd restart && sudo service nmbd restart && sleep 3 )' 2>&1 |
         stdbuf -oL sed -n -e  's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |
         zenity --progress --title="Restarting Network Share Services..." --pulsate --width=600 --auto-close
                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error  --title="Error" --text="Restarting Network Services has failed."
                                        exit
                                fi
                                        zenity --info --title="$TITLE" --window-icon=/usr/share/icons/zenity-llcc.png --text="Network Services restarted successfully."
